name: dotnet package

on:
  push:
    tags:        
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "6.0"
      - name: Build
        run: dotnet publish -p:PublishProfile=FolderProfile
      - name: Generate Hashes
        run: |
          Get-FileHash ./build/GtaVersionSelector.exe | Out-file ./GtaVersionSelector-checksum.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          files: |
            ./*-checksum.txt
            ./build/*.exe
            
