name: dotnet package

on:
  push:
    tags:        
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "6.0"
      - name: Install dependencies
        run: |
          dotnet restore
          sudo apt-get install -y tree
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Tree
        run: tree .